import { useQuery } from "@tanstack/react-query";
import { MPLayout, MPSection, MPEmpty, MPStat, NoExternalActionBanner } from "./_shared";
import { Badge } from "@/components/ui/badge";
import { computeGrowthSnapshot } from "@/lib/marketplaceGrowthEngine";

const statusTone: Record<string, string> = {
  cold_start: "bg-muted text-muted-foreground border-border/60",
  supply_short: "bg-yellow-500/15 text-yellow-300 border-yellow-500/30",
  demand_short: "bg-yellow-500/15 text-yellow-300 border-yellow-500/30",
  balanced: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  oversupplied: "bg-blue-500/15 text-blue-300 border-blue-500/30",
  undersupplied: "bg-orange-500/15 text-orange-300 border-orange-500/30",
  watch: "bg-red-500/15 text-red-300 border-red-500/30",
};

export default function MarketplaceLiquidity() {
  const { data: snap } = useQuery({ queryKey: ["mp-growth-snap"], queryFn: computeGrowthSnapshot, refetchInterval: 60000 });

  return (
    <MPLayout title="Liquidity" subtitle="Single-screen view of supply vs demand health across every category and location cell.">
      <NoExternalActionBanner />
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <MPStat label="Cells tracked" value={snap?.total_cells ?? 0} />
        <MPStat label="Cold start" value={snap?.cold_start ?? 0} tone={snap?.cold_start ? "warn" : "default"} />
        <MPStat label="Supply short" value={snap?.supply_short ?? 0} tone={snap?.supply_short ? "warn" : "default"} />
        <MPStat label="Demand short" value={snap?.demand_short ?? 0} tone={snap?.demand_short ? "warn" : "default"} />
        <MPStat label="Balanced" value={snap?.balanced ?? 0} tone="good" />
        <MPStat label="Oversupplied" value={snap?.oversupplied ?? 0} />
        <MPStat label="Watch" value={snap?.watch ?? 0} tone={snap?.watch ? "bad" : "default"} />
        <MPStat label="Failed match rate" value={`${((snap?.failed_match_rate ?? 0) * 100).toFixed(1)}%`} tone={(snap?.failed_match_rate ?? 0) > 0.2 ? "warn" : "default"} />
      </div>

      <MPSection title="Recommended next action" description="Generated by the Marketplace Growth Agent.">
        <p className="text-sm text-primary/90">{snap?.recommended_action ?? "—"}</p>
      </MPSection>

      <MPSection title="Top supply gaps" description="Highest supply gap scores — recruit sellers here.">
        {!snap || snap.top_supply_gaps.length === 0 ? <MPEmpty title="No supply gaps detected" hint="Liquidity snapshots will populate as marketplace activity is recorded." /> : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead className="text-[10px] uppercase text-muted-foreground"><tr className="border-b border-border/40">
                <th className="text-left p-2">Category</th><th className="text-left p-2">Location</th>
                <th className="text-right p-2">Supply</th><th className="text-right p-2">Demand</th>
                <th className="text-right p-2">Supply gap</th><th className="text-left p-2">Status</th>
              </tr></thead>
              <tbody>
                {snap.top_supply_gaps.map(r => (
                  <tr key={r.id} className="border-b border-border/20">
                    <td className="p-2">{r.category ?? "—"}</td>
                    <td className="p-2">{r.location ?? "—"}</td>
                    <td className="p-2 text-right font-mono">{r.active_supply}</td>
                    <td className="p-2 text-right font-mono">{r.active_demand}</td>
                    <td className="p-2 text-right"><Badge variant="outline" className="text-[10px]">{Number(r.supply_gap_score).toFixed(2)}</Badge></td>
                    <td className="p-2"><Badge variant="outline" className={`text-[10px] ${statusTone[r.liquidity_status] ?? ""}`}>{r.liquidity_status}</Badge></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </MPSection>

      <MPSection title="Top demand gaps" description="Highest demand gap scores — attract buyers here.">
        {!snap || snap.top_demand_gaps.length === 0 ? <MPEmpty title="No demand gaps detected" /> : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead className="text-[10px] uppercase text-muted-foreground"><tr className="border-b border-border/40">
                <th className="text-left p-2">Category</th><th className="text-left p-2">Location</th>
                <th className="text-right p-2">Supply</th><th className="text-right p-2">Demand</th>
                <th className="text-right p-2">Demand gap</th><th className="text-left p-2">Status</th>
              </tr></thead>
              <tbody>
                {snap.top_demand_gaps.map(r => (
                  <tr key={r.id} className="border-b border-border/20">
                    <td className="p-2">{r.category ?? "—"}</td>
                    <td className="p-2">{r.location ?? "—"}</td>
                    <td className="p-2 text-right font-mono">{r.active_supply}</td>
                    <td className="p-2 text-right font-mono">{r.active_demand}</td>
                    <td className="p-2 text-right"><Badge variant="outline" className="text-[10px]">{Number(r.demand_gap_score).toFixed(2)}</Badge></td>
                    <td className="p-2"><Badge variant="outline" className={`text-[10px] ${statusTone[r.liquidity_status] ?? ""}`}>{r.liquidity_status}</Badge></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </MPSection>

      <MPSection title="Failed match reasons" description="Why matches did not complete — fix root causes first.">
        {!snap || Object.keys(snap.failed_reasons).length === 0 ? <MPEmpty title="No failed matches recorded" /> : (
          <div className="flex flex-wrap gap-2">
            {Object.entries(snap.failed_reasons).map(([reason, count]) => (
              <Badge key={reason} variant="outline" className="text-[11px]">{reason}: <span className="ml-1 font-mono">{count}</span></Badge>
            ))}
          </div>
        )}
      </MPSection>
    </MPLayout>
  );
}