import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { INCLayout, INCSection, INCEmpty, NoAutoNoticesBanner } from "./_shared";
import { Badge } from "@/components/ui/badge";

type Incident = { id: string; incident_title: string; severity: string; incident_status: string; customer_notification_required: boolean; regulator_notification_required: boolean; affected_customers_count: number; audit_metadata: any };

export default function IncidentsNotifications() {
  const [incs, setIncs] = useState<Incident[]>([]);
  useEffect(() => {
    (async () => {
      const sb: any = supabase as any;
      const { data } = await sb.from("incident_records").select("id,incident_title,severity,incident_status,customer_notification_required,regulator_notification_required,affected_customers_count,audit_metadata").order("discovered_at", { ascending: false });
      setIncs(data ?? []);
    })();
  }, []);

  const needsNotice = incs.filter(i => (i.customer_notification_required || i.regulator_notification_required) && i.incident_status !== "closed");

  return (
    <INCLayout title="Notification drafts" subtitle="Drafts prepared by the Incident Agent. Nothing is sent until a founder approves it in the Approval Queue.">
      <NoAutoNoticesBanner />
      <INCSection title={`Pending notices (${needsNotice.length})`}>
        {needsNotice.length === 0 ? <INCEmpty title="No notifications drafted" hint="Customer or regulator notice requirements get flagged on incidents and surfaced here." /> : (
          <div className="space-y-2">
            {needsNotice.map(i => {
              const draft = (i.audit_metadata && typeof i.audit_metadata === "object" && "notification_draft" in i.audit_metadata) ? (i.audit_metadata as any).notification_draft : null;
              return (
                <div key={i.id} className="rounded border border-border/50 p-3 space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-medium text-sm">{i.incident_title}</span>
                    <Badge variant="outline" className="text-[10px]">{i.severity}</Badge>
                    {i.customer_notification_required && <Badge variant="outline" className="bg-yellow-500/15 text-yellow-300 border-yellow-500/30 text-[10px]">customer</Badge>}
                    {i.regulator_notification_required && <Badge variant="outline" className="bg-red-500/15 text-red-400 border-red-500/30 text-[10px]">regulator</Badge>}
                    <Badge variant="outline" className="bg-yellow-500/15 text-yellow-300 border-yellow-500/30 text-[10px] ml-auto">awaiting approval</Badge>
                  </div>
                  {i.affected_customers_count > 0 && <p className="text-[11px] text-muted-foreground">~{i.affected_customers_count} customers affected</p>}
                  {draft ? <pre className="text-[11px] whitespace-pre-wrap text-muted-foreground border-l border-primary/40 pl-2 mt-2">{String(draft)}</pre> : <p className="text-[11px] text-muted-foreground italic">Draft will be generated by the Incident Agent.</p>}
                </div>
              );
            })}
          </div>
        )}
      </INCSection>
    </INCLayout>
  );
}