import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface TestResult {
  module: string;
  test_name: string;
  status: "passed" | "failed" | "warning";
  details: string;
  duration_ms: number;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    const results: TestResult[] = [];
    const startTime = Date.now();

    // Helper
    const runTest = async (module: string, name: string, fn: () => Promise<{ ok: boolean; detail: string }>) => {
      const t0 = Date.now();
      try {
        const r = await fn();
        results.push({ module, test_name: name, status: r.ok ? "passed" : "failed", details: r.detail, duration_ms: Date.now() - t0 });
      } catch (e) {
        results.push({ module, test_name: name, status: "failed", details: String(e), duration_ms: Date.now() - t0 });
      }
    };

    // ── 1. Organisation Tests ──
    await runTest("organisations", "Create test organisations", async () => {
      const testOrgs = [
        { name: "Test Financial Services Firm", industry: "Financial Services", status: "active" },
        { name: "Test Healthcare Operations Co", industry: "Healthcare", status: "active" },
        { name: "Test Enterprise Automation Client", industry: "Technology", status: "active" },
      ];
      const { error } = await supabase.from("organisations").upsert(testOrgs, { onConflict: "name" });
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Created ${testOrgs.length} test organisations` };
    });

    await runTest("organisations", "Read organisations", async () => {
      const { data, error } = await supabase.from("organisations").select("id, name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: (data?.length ?? 0) > 0, detail: `Found ${data?.length} organisations` };
    });

    // ── 2. Automation Workflow Tests ──
    await runTest("automations", "Read automation workflows", async () => {
      const { data, error } = await supabase.from("automation_workflows").select("id, name, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} workflows` };
    });

    // ── 3. AI Agent Tests ──
    await runTest("agents", "Read AI agents", async () => {
      const { data, error } = await supabase.from("ai_agents").select("id, name, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} agents` };
    });

    // ── 4. Monitored Systems Tests ──
    await runTest("systems", "Read monitored systems", async () => {
      const { data, error } = await supabase.from("monitored_systems").select("id, system_name, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} monitored systems` };
    });

    // ── 5. Brain Insight Tests ──
    await runTest("brain", "Create test brain insight", async () => {
      const { error } = await supabase.from("brain_insights").insert({
        title: "[TEST] Performance anomaly detected",
        description: "Test insight generated by platform validation suite",
        insight_type: "performance",
        priority: "low",
        source_module: "Platform Testing Suite",
        status: "new",
      });
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: "Test brain insight created" };
    });

    await runTest("brain", "Read brain insights", async () => {
      const { data, error } = await supabase.from("brain_insights").select("id, title").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: (data?.length ?? 0) > 0, detail: `Found ${data?.length} brain insights` };
    });

    await runTest("brain", "Read brain recommendations", async () => {
      const { data, error } = await supabase.from("brain_recommendations").select("id, title").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} recommendations` };
    });

    await runTest("brain", "Read brain learning records", async () => {
      const { data, error } = await supabase.from("brain_learning_records").select("id").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} learning records` };
    });

    // ── 6. Decision Engine Tests ──
    await runTest("decisions", "Create test decision recommendation", async () => {
      const { error } = await supabase.from("decision_recommendations").insert({
        title: "[TEST] Optimise document workflow",
        description: "Test recommendation from validation suite",
        category: "operational",
        priority: "low",
        status: "pending",
        potential_benefits: "Improved processing speed",
        potential_risks: "None - test data",
        target_module: "workflows",
      });
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: "Test decision recommendation created" };
    });

    await runTest("decisions", "Read decision recommendations", async () => {
      const { data, error } = await supabase.from("decision_recommendations").select("id, title, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: (data?.length ?? 0) > 0, detail: `Found ${data?.length} decision recommendations` };
    });

    // ── 7. Strategy Engine Tests ──
    await runTest("strategy", "Create test strategy insight", async () => {
      const { error } = await supabase.from("strategy_insights").insert({
        title: "[TEST] High demand for compliance automation",
        description: "Test strategic insight from validation suite",
        category: "market_signal",
        confidence_level: "medium",
        target_industry: "Financial Services",
        status: "pending",
      });
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: "Test strategy insight created" };
    });

    await runTest("strategy", "Read strategy insights", async () => {
      const { data, error } = await supabase.from("strategy_insights").select("id, title").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: (data?.length ?? 0) > 0, detail: `Found ${data?.length} strategy insights` };
    });

    // ── 8. Deployment Tests ──
    await runTest("deployments", "Read deployments", async () => {
      const { data, error } = await supabase.from("deployments").select("id, system_name, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} deployments` };
    });

    // ── 9. Architecture Tests ──
    await runTest("architectures", "Read architectures", async () => {
      const { data, error } = await supabase.from("architectures").select("id, name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} architectures` };
    });

    // ── 10. Template Tests ──
    await runTest("templates", "Read system templates", async () => {
      const { data, error } = await supabase.from("system_templates").select("id, name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} templates` };
    });

    // ── 11. Knowledge Base Tests ──
    await runTest("knowledge", "Read knowledge entries", async () => {
      const { data, error } = await supabase.from("knowledge_entries").select("id, title").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} knowledge entries` };
    });

    // ── 12. Integration Tests ──
    await runTest("integrations", "Read integrations", async () => {
      const { data, error } = await supabase.from("integrations").select("id, name, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} integrations` };
    });

    // ── 13. Build Log Tests ──
    await runTest("build_log", "Create test build log entry", async () => {
      const { error } = await supabase.from("build_log_entries").insert({
        title: "[TEST] Platform validation run",
        description: "Automated test entry from platform validation suite",
        change_type: "test_run",
        module_affected: "Platform Testing Suite",
        author: "Liftor AI Testing",
      });
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: "Test build log entry created" };
    });

    // ── 14. Optimisation Tests ──
    await runTest("optimisation", "Read optimisation insights", async () => {
      const { data, error } = await supabase.from("optimisation_insights").select("id, title").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} optimisation insights` };
    });

    // ── 15. Access Control Tests ──
    await runTest("security", "Read platform roles", async () => {
      const { data, error } = await supabase.from("platform_roles").select("id, name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} platform roles` };
    });

    await runTest("security", "Read access audit log", async () => {
      const { data, error } = await supabase.from("access_audit_log").select("id").limit(5);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} audit log entries` };
    });

    // ── 16. Data Integrity Tests ──
    await runTest("data_integrity", "Check workflow-system references", async () => {
      const { data, error } = await supabase.from("automation_workflows").select("id, system_id").limit(50);
      if (error) return { ok: false, detail: error.message };
      if (!data || data.length === 0) return { ok: true, detail: "No workflows to validate" };
      const systemIds = [...new Set(data.map(w => w.system_id))];
      const { data: systems, error: sErr } = await supabase.from("monitored_systems").select("id").in("id", systemIds);
      if (sErr) return { ok: false, detail: sErr.message };
      const orphans = systemIds.length - (systems?.length ?? 0);
      return { ok: orphans === 0, detail: orphans > 0 ? `${orphans} orphan workflow references` : "All workflow references valid" };
    });

    await runTest("data_integrity", "Check agent-system references", async () => {
      const { data, error } = await supabase.from("ai_agents").select("id, system_id").limit(50);
      if (error) return { ok: false, detail: error.message };
      if (!data || data.length === 0) return { ok: true, detail: "No agents to validate" };
      const systemIds = [...new Set(data.map(a => a.system_id))];
      const { data: systems, error: sErr } = await supabase.from("monitored_systems").select("id").in("id", systemIds);
      if (sErr) return { ok: false, detail: sErr.message };
      const orphans = systemIds.length - (systems?.length ?? 0);
      return { ok: orphans === 0, detail: orphans > 0 ? `${orphans} orphan agent references` : "All agent references valid" };
    });

    // ── 17. Manual Tests ──
    await runTest("manual", "Read manual pages", async () => {
      const { data, error } = await supabase.from("manual_pages").select("id, module_name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} manual pages` };
    });

    // ── 18. Execution Tests ──
    await runTest("executions", "Read workflow executions", async () => {
      const { data, error } = await supabase.from("workflow_executions").select("id, status").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} workflow executions` };
    });

    // ── 19. Launched Platforms Tests ──
    await runTest("expansion", "Read launched platforms", async () => {
      const { data, error } = await supabase.from("launched_platforms").select("id, name").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} launched platforms` };
    });

    // ── 20. Compliance Tests ──
    await runTest("security", "Read compliance items", async () => {
      const { data, error } = await supabase.from("compliance_items").select("id, area").limit(10);
      if (error) return { ok: false, detail: error.message };
      return { ok: true, detail: `Found ${data?.length ?? 0} compliance items` };
    });

    // ── 21. AI Proposal Generator Test ──
    await runTest("ai_proposal", "AI Proposal Generator Test", async () => {
      const t0 = Date.now();
      const testPayload = {
        projectTypes: ["automation platform"],
        businessProblem: "Manual operational processes creating inefficiencies",
        processesToAutomate: ["document processing", "customer onboarding", "report generation"],
        projectScale: "mid-size organisation",
        timeline: "3-6 months",
        industry: "financial services",
      };

      const proposalResponse = await fetch(`${supabaseUrl}/functions/v1/generate-proposal`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${serviceRoleKey}`,
        },
        body: JSON.stringify(testPayload),
      });

      const responseTime = (Date.now() - t0) / 1000;
      const responseText = await proposalResponse.text();

      if (!proposalResponse.ok) {
        return { ok: false, detail: `HTTP ${proposalResponse.status} — ${responseText.substring(0, 200)}` };
      }

      let proposalData;
      try {
        proposalData = JSON.parse(responseText);
      } catch {
        return { ok: false, detail: "Response is not valid JSON" };
      }

      if (proposalData.error) {
        return { ok: false, detail: `Edge function error: ${proposalData.error}` };
      }

      const hasSolution = typeof proposalData.suggested_solution === "string" && proposalData.suggested_solution.length > 0;
      const hasScope = typeof proposalData.estimated_scope === "string" && proposalData.estimated_scope.length > 0;
      const hasTimeline = typeof proposalData.estimated_timeline === "string" && proposalData.estimated_timeline.length > 0;

      if (!hasSolution || !hasScope || !hasTimeline) {
        const missing = [];
        if (!hasSolution) missing.push("suggested_solution");
        if (!hasScope) missing.push("estimated_scope");
        if (!hasTimeline) missing.push("estimated_timeline");
        return { ok: false, detail: `Missing fields: ${missing.join(", ")}` };
      }

      if (responseTime > 10) {
        return { ok: false, detail: `Response time ${responseTime.toFixed(1)}s exceeds 10s limit` };
      }

      return { ok: true, detail: `Response time: ${responseTime.toFixed(1)}s — All output fields verified` };
    });

    // ── 22. AI Proposal Schema Integrity Test ──
    await runTest("ai_proposal", "AI Proposal Schema Integrity Test", async () => {
      const testPayload = {
        projectTypes: ["automation platform"],
        businessProblem: "Manual operational processes creating inefficiencies",
        processesToAutomate: ["document processing", "customer onboarding", "report generation"],
        projectScale: "mid-size organisation",
        timeline: "3-6 months",
        industry: "financial services",
      };

      const res = await fetch(`${supabaseUrl}/functions/v1/generate-proposal`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${serviceRoleKey}`,
        },
        body: JSON.stringify(testPayload),
      });

      const rawText = await res.text();

      // 1. Valid JSON
      let parsed;
      try {
        parsed = JSON.parse(rawText);
      } catch {
        console.error("[Schema Integrity] Malformed JSON response:", rawText.substring(0, 500));
        return { ok: false, detail: "Response is not valid JSON" };
      }

      // 2. Response length
      if (rawText.length > 10000) {
        console.error("[Schema Integrity] Response exceeds 10,000 chars:", rawText.length);
        return { ok: false, detail: `Response too large: ${rawText.length} characters` };
      }

      const requiredFields = ["suggested_solution", "estimated_scope", "estimated_timeline"] as const;
      const issues: string[] = [];

      for (const field of requiredFields) {
        // 3. Field exists
        if (!(field in parsed)) {
          issues.push(`${field}: missing`);
          continue;
        }
        // 4. Not null
        if (parsed[field] === null) {
          issues.push(`${field}: null`);
          continue;
        }
        // 5. Is string
        if (typeof parsed[field] !== "string") {
          issues.push(`${field}: type is ${typeof parsed[field]}, expected string`);
          continue;
        }
        // 6. Not empty
        if (parsed[field].trim().length === 0) {
          issues.push(`${field}: empty string`);
          continue;
        }
        // 7. Min length
        if (parsed[field].length < 10) {
          issues.push(`${field}: too short (${parsed[field].length} chars)`);
        }
      }

      if (issues.length > 0) {
        console.error("[Schema Integrity] Validation failed:", JSON.stringify(issues), "Response:", rawText.substring(0, 500));
        return { ok: false, detail: `Schema violations: ${issues.join("; ")}` };
      }

      // Check no unexpected top-level keys
      const extraKeys = Object.keys(parsed).filter(k => !requiredFields.includes(k as any));

      return { ok: true, detail: `Fields verified: 3 — Schema valid: Yes${extraKeys.length > 0 ? ` (${extraKeys.length} extra keys ignored)` : ""}` };
    });

    // ── 23. AI Proposal Response Timeout Test ──
    await runTest("ai_proposal", "AI Proposal Response Timeout Test", async () => {
      const t0 = Date.now();
      const testPayload = {
        projectTypes: ["automation platform"],
        businessProblem: "Manual operational processes creating inefficiencies",
        processesToAutomate: ["document processing", "customer onboarding", "report generation"],
        projectScale: "mid-size organisation",
        timeline: "3-6 months",
        industry: "financial services",
      };

      const res = await fetch(`${supabaseUrl}/functions/v1/generate-proposal`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${serviceRoleKey}`,
        },
        body: JSON.stringify(testPayload),
      });

      const responseTime = (Date.now() - t0) / 1000;
      await res.text();

      if (responseTime > 20) {
        console.error(`[Timeout Test] Response exceeded 20s: ${responseTime.toFixed(1)}s`);
        return { ok: false, detail: `Response time: ${responseTime.toFixed(1)}s — exceeds 20s limit` };
      }

      if (responseTime > 10) {
        console.warn(`[Timeout Test] Slow response: ${responseTime.toFixed(1)}s`);
        results.pop(); // remove the auto-added result from runTest so we can push warning manually
        results.push({ module: "ai_proposal", test_name: "AI Proposal Response Timeout Test", status: "warning", details: `Response time: ${responseTime.toFixed(1)}s — exceeds 10s recommended limit`, duration_ms: Date.now() - t0 });
        return { ok: true, detail: "" }; // won't be used since we pushed manually
      }

      return { ok: true, detail: `Response time: ${responseTime.toFixed(1)}s` };
    });

    const failed = results.filter(r => r.status === "failed").length;
    const warnings = results.filter(r => r.status === "warning").length;

    const { data: run, error: runErr } = await supabase.from("platform_test_runs").insert({
      run_name: "Full Platform Validation",
      status: failed > 0 ? "failed" : "passed",
      total_tests: results.length,
      passed,
      failed,
      warnings,
      completed_at: new Date().toISOString(),
    }).select("id").single();

    if (runErr) throw runErr;

    const testRecords = results.map(r => ({ ...r, run_id: run.id }));
    await supabase.from("platform_test_results").insert(testRecords);

    // Clean up test data
    await supabase.from("brain_insights").delete().like("title", "[TEST]%");
    await supabase.from("decision_recommendations").delete().like("title", "[TEST]%");
    await supabase.from("strategy_insights").delete().like("title", "[TEST]%");
    await supabase.from("build_log_entries").delete().like("title", "[TEST]%");

    return new Response(JSON.stringify({
      run_id: run.id,
      total: results.length,
      passed,
      failed,
      warnings,
      duration_ms: Date.now() - startTime,
      results,
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });

  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
