export type SeedRecord = {
  contact_name: string;
  organisation_name?: string;
  email?: string;
  phone?: string;
  website?: string;
  jurisdiction?: string;
  city_country?: string;
  relationship_type: string;
  relationship_status: string;
  opportunity_role: string;
  trust_level: string;
  disclosure_level: string;
  commercial_value_score: number;
  strategic_value_score: number;
  urgency_score: number;
  next_action_summary?: string;
  source: string;
  source_notes?: string;
  meeting_summary?: string;
  ai_summary?: string;
  founder_notes?: string;
  tags: string[];
};

export const RELATIONSHIP_SEED: SeedRecord[] = [
  {
    contact_name: "Adrian Benosiglio",
    organisation_name: "RSM UK",
    email: "Adrian.Benosiglio@rsmuk.com",
    phone: "+44 7455 249249",
    website: "https://www.rsmuk.com",
    jurisdiction: "UK / international",
    relationship_type: "legal_tax_contact",
    relationship_status: "meeting_booked",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 5,
    source: "manual",
    next_action_summary: "After 10 Jun 2026 call, request written phase-one scope, named team, jurisdictions covered, fee range and how RSM coordinates advice across member firms.",
    ai_summary: "RSM UK tax partner. Possible UK-led coordinator for international tax/accounting across UK, US/Delaware, UAE/Dubai and Malta. Has linked in Kenneth at RSM Malta and Jill Kaur.",
    founder_notes: "Direct line +44 20 3201 8694. Initial UK-led overview call 10 Jun 2026 14:15 UK with Adrian and Jill. Do not disclose full Liftor architecture, net worth, bank details, full exit targets or detailed tax/extraction strategy before engagement route is clear.",
    tags: ["rsm","tax","legal","nda-required","follow-up"],
  },
  {
    contact_name: "Jill Kaur",
    organisation_name: "RSM UK",
    email: "Jill.Kaur@rsmuk.com",
    jurisdiction: "UK / international",
    relationship_type: "legal_tax_contact",
    relationship_status: "active",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 4,
    source: "manual",
    next_action_summary: "Assess fit during RSM overview call and decide whether she becomes core personal/international mobility adviser route.",
    ai_summary: "Brought in by Adrian Benosiglio. Specialises in HNW and internationally mobile families across Europe, Far East and USA.",
    founder_notes: "Relevant for personal residence planning, family protection, succession, school-fee funding and founder/business-owner tax position. NDA/engagement before detailed family wealth disclosure.",
    tags: ["rsm","tax","iht","succession","nda-required","follow-up"],
  },
  {
    contact_name: "Timothy Zammit",
    organisation_name: "RSM Malta",
    email: "Timothy.Zammit@rsm.com.mt",
    jurisdiction: "Malta",
    relationship_type: "legal_tax_contact",
    relationship_status: "warm",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 3,
    source: "manual",
    next_action_summary: "Keep copied. Bring into follow-up scoping call if RSM UK confirms wider joined-up route.",
    ai_summary: "Principal - Tax at RSM Malta. Offered to join meeting if useful; happy for UK-led overview first.",
    founder_notes: "Treat Malta as one possible residence/local tax jurisdiction, not the sole issue.",
    tags: ["rsm","malta","tax","nda-required","follow-up"],
  },
  {
    contact_name: "Kenneth Cremona",
    organisation_name: "RSM Malta",
    email: "kenneth.cremona@rsm.com.mt",
    jurisdiction: "Malta",
    relationship_type: "legal_tax_contact",
    relationship_status: "warm",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 3,
    source: "manual",
    next_action_summary: "Bring into joined-up follow-up if RSM progresses.",
    ai_summary: "RSM Malta colleague copied by Timothy and spoken to by Adrian. Useful engagement signal from RSM Malta.",
    founder_notes: "Agreed UK-led call first before wider RSM teams join.",
    tags: ["rsm","malta","tax","follow-up"],
  },
  {
    contact_name: "Mark Attard",
    organisation_name: "BDO Malta",
    email: "mark.attard@bdo.com.mt",
    phone: "+356 9942 1750",
    website: "https://www.bdo.com.mt",
    jurisdiction: "Malta / international",
    relationship_type: "legal_tax_contact",
    relationship_status: "onboarding_pending",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 5,
    source: "manual",
    next_action_summary: "Await NDA/onboarding and initial quote for Malta residence/family position. Later request business/cross-border structure scope and fee.",
    ai_summary: "CEO at BDO Malta. Confirmed BDO Malta can coordinate with BDO UK, US and UAE via Malta as lead route. Next step NDA and onboarding.",
    founder_notes: "Direct line +356 2342 4218. Mandy confirmed happy for BDO Malta to proceed with NDA/onboarding, provided scope remains joined-up international, not only Malta residence. Do not share detailed documents until NDA/onboarding route is clear.",
    tags: ["bdo","malta","tax","legal","nda-required","follow-up"],
  },
  {
    contact_name: "Audrey Azzopardi",
    organisation_name: "BDO Malta",
    email: "audrey.azzopardi@bdo.com.mt",
    jurisdiction: "Malta",
    relationship_type: "legal_tax_contact",
    relationship_status: "onboarding_pending",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 4,
    source: "manual",
    next_action_summary: "Await onboarding/NDA and clarify exact role in leading the engagement.",
    ai_summary: "Identified by Mark Attard as Mandy's lead partner at BDO Malta. Relevant for Malta residence, family relocation and wider BDO coordination.",
    founder_notes: "Keep separate from RSM route until adviser decision is made.",
    tags: ["bdo","malta","tax","nda-required","follow-up"],
  },
  {
    contact_name: "Saurbh Kothari",
    organisation_name: "Afridi & Angell",
    email: "saurbh@afridi-angell.com",
    phone: "+971 4 330 3900",
    website: "https://www.afridi-angell.com",
    jurisdiction: "UAE / Dubai",
    city_country: "Dubai, UAE",
    relationship_type: "legal_tax_contact",
    relationship_status: "active",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 5,
    source: "manual",
    next_action_summary: "Request written scope/fee if progressing. Keep warm as UAE legal contact.",
    ai_summary: "Partner at Afridi & Angell. Important UAE legal route for Zorvian Management Consultants FZCO, IFZA licence, substance, governance, intercompany agreements, management fees/cost recharges and corporate structuring.",
    founder_notes: "Fax +971 4 330 3800. Address: Jumeirah Emirates Towers, Office Tower, Level 35, Sheikh Zayed Road, PO Box 9371, Dubai, UAE. Positive meeting. No full Liftor architecture, banking, tax extraction plan, estate details or AI portfolio until engagement/NDA is clear.",
    tags: ["uae","legal","nda-required","follow-up"],
  },
  {
    contact_name: "Arpita Kaul",
    organisation_name: "Easy Assist UAE",
    email: "arpita@easyassist.ae",
    jurisdiction: "UAE",
    relationship_type: "operations_support",
    relationship_status: "onboarding_pending",
    opportunity_role: "supplier",
    trust_level: "low",
    disclosure_level: "restricted",
    commercial_value_score: 4, strategic_value_score: 4, urgency_score: 4,
    source: "manual",
    next_action_summary: "Await proposed VA profile, working hours, sample daily log, contract/service terms, NDA/confidentiality, first-month trial confirmation, payment/invoicing and start date.",
    ai_summary: "UAE VA / operations support. 2 hrs/day x 5 days/week ≈ AED 3,000/month. Dedicated VA. Can support Gmail, Drive, CRMs, spreadsheets, task tracking, daily logs and controlled admin.",
    founder_notes: "Missed/rescheduled call (daughter unwell); may rebook via Calendly. Trial only. No passwords, no banking, no client data, no external sending, no sensitive access at start. Gradual controlled access.",
    tags: ["va","operations-support","uae","restricted-disclosure","follow-up"],
  },
  {
    contact_name: "Craig Bartley",
    organisation_name: "Amber River SFIA / SFIA Wealth Management Ltd",
    email: "craigb@amberriversfia.com",
    phone: "01628 566777",
    website: "https://www.amberriver.com/sfia",
    jurisdiction: "UK",
    city_country: "Maidenhead, Berkshire, UK",
    relationship_type: "school_education_contact",
    relationship_status: "meeting_booked",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "light_context",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 5,
    source: "manual",
    next_action_summary: "Prepare Jag and Mandy for 17 Jun 2026 12:00 Teams meeting. Do not commit to paid advice unless Craig clearly explains output, scope and value.",
    ai_summary: "Independent Financial Planner specialising in school-fees planning. Advice fee £750 after consultation if proceeding.",
    founder_notes: "Mobile 07782 129321. Address: 27 Moorbridge Road, Maidenhead, Berkshire, SL6 8LT. Bring income, expenditure, assets, liabilities, pensions and protection arrangements. Light financial context only at first; no sensitive documents until scope is clear.",
    tags: ["school-fees","finance","follow-up"],
  },
  {
    contact_name: "Douglas Edmunds",
    organisation_name: "CapEQ",
    email: "douglas.edmunds@capeq.com",
    phone: "+44 7785 287187",
    website: "https://capeq.com",
    jurisdiction: "UK",
    relationship_type: "m_and_a_contact",
    relationship_status: "warm",
    opportunity_role: "adviser",
    trust_level: "high",
    disclosure_level: "confidential_allowed",
    commercial_value_score: 5, strategic_value_score: 5, urgency_score: 4,
    source: "manual",
    next_action_summary: "Await CapEQ feedback and keep relationship warm.",
    ai_summary: "Partner at CapEQ. Understood AI Brain / Liftor model and strategic exit thinking. NDA executed. Strong keep-warm for M&A, capital, growth, investor/saleability and exit-readiness.",
    founder_notes: "Office +44 20 8004 3463. Mandy sent controlled category-level summary for internal CapEQ review. NDA signed — keep disclosure controlled and category-level unless clear advisory scope agreed.",
    tags: ["m-and-a","capeq","follow-up"],
  },
  {
    contact_name: "Ben Rosen",
    organisation_name: "Quastels",
    email: "brosen@quastels.com",
    jurisdiction: "UK",
    relationship_type: "legal_tax_contact",
    relationship_status: "active",
    opportunity_role: "adviser",
    trust_level: "high",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 5,
    source: "manual",
    next_action_summary: "Await fee proposal / next step on school-fee funding and wider private client structure.",
    ai_summary: "Private wealth legal adviser. Strong fit for wills, trusts, IHT, Christine protection, digital/AI asset succession, property, business ownership governance and family wealth planning. Confirmed school-fee funding within expertise.",
    founder_notes: "Assistant/cc Emily Smith <esmith@quastels.com>. Legal/private wealth lane — keep separate from tax/accounting routes.",
    tags: ["legal","iht","trust","succession","christine-protection","school-fees","nda-required","follow-up"],
  },
  {
    contact_name: "Arham Siddiqui / CICL UK",
    organisation_name: "CICL UK",
    email: "info@cicluk.co.uk",
    phone: "+44 20 7870 1537",
    website: "https://www.cicluk.co.uk",
    jurisdiction: "UK / Kenya",
    city_country: "London E14 4QZ",
    relationship_type: "government_trade_route",
    relationship_status: "meeting_booked",
    opportunity_role: "introducer",
    trust_level: "medium",
    disclosure_level: "public_only",
    commercial_value_score: 4, strategic_value_score: 5, urgency_score: 5,
    source: "event",
    next_action_summary: "Attend 11 Jun 2026 13:30 InterContinental London – The O2 meeting. Capture names, roles, follow-up routes and any suggested agencies/partners.",
    ai_summary: "CICL contact for Kenya–UK Global Mission 2026. Mandy pre-selected for exclusive meeting with senior Government of Kenya officials and H.E. Maurice Makoloo. Route for Kenya market-entry intelligence, government introductions and Africa-facing network building.",
    founder_notes: "Address: 25 Cabot Square, London, E14 4QZ. Form complete and profile uploaded. Public founder profile only. Do not disclose full Liftor architecture, confidential corporate/tax structure or personal wealth details.",
    tags: ["kenya","trade-mission","follow-up"],
  },
  {
    contact_name: "Alexia Hathout",
    organisation_name: "Belair Property St. Julian's",
    email: "Alexia@belair.com.mt",
    phone: "+356 20118200",
    jurisdiction: "Malta",
    city_country: "St. Julian's, Malta",
    relationship_type: "property_residency_route",
    relationship_status: "active",
    opportunity_role: "supplier",
    trust_level: "medium",
    disclosure_level: "light_context",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 4,
    source: "manual",
    next_action_summary: "Await viewing shortlist and area guidance for July Malta trip.",
    ai_summary: "Senior Property Consultant, Belair Property St. Julian's. Useful for Malta property viewings, school-friendly areas, rental/resale potential and local market intelligence.",
    founder_notes: "Mobile +356 99421564. Address: 3/4, St. George's Road, St. Julian's, STJ 3208, Malta. Exploring purchase/investment not rental. Preferred budget ~€300k, up to €500k only for strong property/location/value. Older/second-user preferred. Do not disclose full wealth, full tax/residency plan or future sale/exit planning.",
    tags: ["malta","property","follow-up"],
  },
  {
    contact_name: "Michael Frimpong",
    organisation_name: "Enness Global",
    email: "mf@enness.co.uk",
    phone: "+44 7464 480 089",
    website: "https://www.ennessglobal.com",
    jurisdiction: "UK",
    relationship_type: "finance_route",
    relationship_status: "parked",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "light_context",
    commercial_value_score: 4, strategic_value_score: 3, urgency_score: 2,
    source: "manual",
    next_action_summary: "Park for now. Revisit Global Wealth Statement when tax/legal structuring is further advanced.",
    ai_summary: "Partner at Enness. Relevant for property/development/refinance route and potential future liquidity/finance structuring. Has resent Global Wealth Statement for completion.",
    founder_notes: "Do not upload full wealth data until strategic finance need is clear and aligned with adviser structure.",
    tags: ["finance","follow-up"],
  },
  {
    contact_name: "Laura Hutchinson",
    organisation_name: "Forbes Dawson",
    email: "laura@forbesdawson.co.uk",
    phone: "0161 927 9277",
    website: "https://www.forbesdawson.co.uk",
    jurisdiction: "UK",
    city_country: "Altrincham, UK",
    relationship_type: "legal_tax_contact",
    relationship_status: "active",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "light_context",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 3,
    source: "referral",
    next_action_summary: "Await booking / introductory 15-minute fit call before any paid preliminary review.",
    ai_summary: "Managing Partner at Forbes Dawson. UK private client tax, trust tax, IHT, Life Interest Trust, Business Property Trust / BPR and cross-border UK/UAE context. Free 15-min intro; minimum engagement fee £1,000 + VAT.",
    founder_notes: "Direct line 0161 927 3853. Mobile 07540 470354. Address: Fairbank House, 27 Ashley Road, Altrincham, WA14 2DP. Introduced by Sally Thornton (More Than Accountants UAE). No confidential documents before engagement route clear.",
    tags: ["tax","iht","trust","follow-up"],
  },
  {
    contact_name: "Sally Thornton",
    organisation_name: "More Than Accountants UAE",
    email: "sally.thornton@morethanaccountants.ae",
    jurisdiction: "UAE",
    relationship_type: "referral_partner",
    relationship_status: "warm",
    opportunity_role: "introducer",
    trust_level: "medium",
    disclosure_level: "light_context",
    commercial_value_score: 3, strategic_value_score: 3, urgency_score: 2,
    source: "manual",
    next_action_summary: "Keep warm; no immediate action.",
    ai_summary: "New Business Manager at More Than Accountants UAE. Introduced Laura Hutchinson (Forbes Dawson). Useful UAE accountant/introduction route.",
    founder_notes: "Do not over-rely for complex international structure; useful for UAE compliance/admin and introductions.",
    tags: ["uae","tax"],
  },
  {
    contact_name: "Elizabeth Regan",
    organisation_name: "Howden Life & Health",
    email: "elizabeth.regan@howdenlifeandhealth.co.uk",
    jurisdiction: "UK",
    relationship_type: "operations_support",
    relationship_status: "waiting_on_them",
    opportunity_role: "supplier",
    trust_level: "medium",
    disclosure_level: "restricted",
    commercial_value_score: 3, strategic_value_score: 3, urgency_score: 3,
    source: "manual",
    next_action_summary: "Confirm medical answers before final submission.",
    ai_summary: "Handling medical questionnaires / protection underwriting route. Relevant to life insurance/protection clean-up.",
    founder_notes: "Do not treat 'To Confirm' responses as final until confirmed diagnoses/conditions are checked. Sensitive medical data — restricted disclosure. Do not store detailed medical information in general relationship notes.",
    tags: ["insurance","restricted-disclosure","follow-up"],
  },
  {
    contact_name: "Natasha Southam",
    organisation_name: "Seddons GSC",
    email: "natasha.southam@seddons-gsc.com",
    jurisdiction: "UK",
    relationship_type: "legal_tax_contact",
    relationship_status: "parked",
    opportunity_role: "adviser",
    trust_level: "medium",
    disclosure_level: "nda_before_detail",
    commercial_value_score: 3, strategic_value_score: 4, urgency_score: 3,
    source: "manual",
    next_action_summary: "Park for now. Revisit AML and engagement terms when ready.",
    ai_summary: "Seddons GSC contact for Will and LPA work. Relevant to family protection, Christine protection, IHT and legal documentation.",
    founder_notes: "Formal terms and AML/Legal ID request received. Parked temporarily — requires passport/AML action. Do not upload passport/ID into Liftor. Track only that AML is pending.",
    tags: ["legal","iht","succession","christine-protection","nda-required","follow-up"],
  },
];