-- Stage 1B live catalog evidence capture (READ ONLY).
-- Run with an authorized read-only database role. Do not run a migration here.
-- psql example: psql "$DATABASE_URL" -X -v ON_ERROR_STOP=1 --csv -f scripts/stage1b-live-catalog-evidence.sql > stage1b-live-catalog-evidence.csv
-- The file emits: (1) exact catalog/ACL/effective-execute metadata for every public function,
-- (2) the exact current anon application function signatures joined to the frozen class registry,
-- (3) exact pg_get_functiondef output for every function body changed by the candidate migration.
-- It also preserves ACL-array ordinals so rollback ordering can be checked against raw proacl text.

\set ON_ERROR_STOP on

WITH classified(typed_signature, classification) AS (
  VALUES
    ('public._is_founder_or_admin()', 'DB_INTERNAL'),
    ('public.accept_proposal_by_token(text)', 'PUBLIC_ANON'),
    ('public.acquire_ai_lease(text, uuid, uuid, integer, integer, text, text, integer)', 'SERVICE_ROLE_INTERNAL'),
    ('public.activate_outreach_campaign(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.ai_actions_today(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_release(text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_reserve(text, text, integer, text, uuid, text, text[], jsonb)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_settle(text, integer, text[], text[], jsonb)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_status()', 'FOUNDER_ADMIN_ONLY'),
    ('public.apollo_decrypt_key(bytea, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_encrypt_key(text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apply_reply_stop_suppression(uuid, text, text)', 'DEAD_OR_LEGACY'),
    ('public.apply_reputation_event(uuid, uuid, reputation_event_type, text)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.assign_inbox_for_contact(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.auto_create_exit_intelligence_profile()', 'DB_INTERNAL'),
    ('public.auto_partial_rebuild()', 'DEAD_OR_LEGACY'),
    ('public.auto_resolve_system_events()', 'DB_INTERNAL'),
    ('public.bi_normalize_name(text)', 'DB_INTERNAL'),
    ('public.binary_quantize(halfvec)', 'DB_INTERNAL'),
    ('public.binary_quantize(vector)', 'DB_INTERNAL'),
    ('public.block_activation_log_mutation()', 'DB_INTERNAL'),
    ('public.bump_inbox_send_count()', 'DB_INTERNAL'),
    ('public.bump_rule_hit_count()', 'DB_INTERNAL'),
    ('public.cancel_queue_on_inbound_comm()', 'DB_INTERNAL'),
    ('public.cancel_queue_on_reply()', 'DB_INTERNAL'),
    ('public.check_outreach_allowed(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.check_outreach_allowed(uuid, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.check_send_throttle(uuid, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.claim_portfolio_contact(uuid, text, text, uuid, boolean, text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.cleanup_stale_ai_leases()', 'FOUNDER_ADMIN_ONLY'),
    ('public.compare_system_versions(integer, integer)', 'FOUNDER_ADMIN_ONLY'),
    ('public.compliance_check_assignment(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_contact(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_demo(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_invoice(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_outbound_communication(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_payment(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_proposal(uuid)', 'DB_INTERNAL'),
    ('public.compliance_score_for(text, uuid)', 'DB_INTERNAL'),
    ('public.compute_assignment_sla(date, assignment_status)', 'DB_INTERNAL'),
    ('public.compute_intent_score(uuid)', 'DB_INTERNAL'),
    ('public.compute_system_health()', 'DB_INTERNAL'),
    ('public.cosine_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.cosine_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.cosine_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.country_to_timezone(text)', 'DB_INTERNAL'),
    ('public.crm_match_interaction_preview(uuid, uuid, text, text, text, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.current_worker_id()', 'DB_INTERNAL'),
    ('public.customer_sales_link_contact_by_email(text)', 'WEBHOOK_SYSTEM'),
    ('public.derive_billionaire_route_evidence_states()', 'DB_INTERNAL'),
    ('public.detect_anomalies()', 'FOUNDER_ADMIN_ONLY'),
    ('public.detect_orphan_content()', 'FOUNDER_ADMIN_ONLY'),
    ('public.domain_for_inbox(uuid)', 'DB_INTERNAL'),
    ('public.eligible_suppliers_for_deal(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.enforce_founder_approval_for_buyer_outreach()', 'DB_INTERNAL'),
    ('public.enforce_founder_approval_for_warm_up_action()', 'DB_INTERNAL'),
    ('public.enforce_inbox_ramp(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.enrich_all_contacts()', 'DEAD_OR_LEGACY'),
    ('public.enrich_contact(uuid)', 'DB_INTERNAL'),
    ('public.escalate_retry_failure(uuid)', 'DEAD_OR_LEGACY'),
    ('public.evaluate_ai_reply(text)', 'DEAD_OR_LEGACY'),
    ('public.expire_demos()', 'DB_INTERNAL'),
    ('public.expire_inactive_conversations()', 'SERVICE_ROLE_INTERNAL'),
    ('public.export_full_system_snapshot()', 'FOUNDER_ADMIN_ONLY'),
    ('public.finance_mark_overdue_invoices()', 'SERVICE_ROLE_INTERNAL'),
    ('public.finance_target_vs_actual(text, date)', 'FOUNDER_ADMIN_ONLY'),
    ('public.flag_idle_assignments()', 'DEAD_OR_LEGACY'),
    ('public.founder_confirm_assignment(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.generate_invoice_number()', 'DEAD_OR_LEGACY'),
    ('public.generate_system_tasks_from_priority(priority_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.get_active_execution_mode(text)', 'DB_INTERNAL'),
    ('public.get_business_outbound_status(text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_contact_360_summary(uuid, uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_contact_timeline(uuid, uuid, integer)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_interaction_ledger_summary(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_relationship_timeline(uuid, integer)', 'DEAD_OR_LEGACY'),
    ('public.get_customer_quarterly_report_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_customer_survey_request_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_inbox_credentials_for_send(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_inbox_imap_credentials(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_outbound_status()', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_outreach_send_cron_status()', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_proposal_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_system_mode()', 'DB_INTERNAL'),
    ('public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gin_extract_value_trgm(text, internal)', 'DB_INTERNAL'),
    ('public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gsm_mailbox_is_campaign_ready(text, text, text, text, text, text, integer, integer, boolean, boolean, text, text, text)', 'DEAD_OR_LEGACY'),
    ('public.gsm_touch_updated_at()', 'DB_INTERNAL'),
    ('public.gtrgm_compress(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_consistent(internal, text, smallint, oid, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_decompress(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_distance(internal, text, smallint, oid, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_in(cstring)', 'DB_INTERNAL'),
    ('public.gtrgm_options(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_out(gtrgm)', 'DB_INTERNAL'),
    ('public.gtrgm_penalty(internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_picksplit(internal, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_same(gtrgm, gtrgm, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_union(internal, internal)', 'DB_INTERNAL'),
    ('public.guard_assignment_creation()', 'DB_INTERNAL'),
    ('public.guard_assignment_supplier_approved()', 'DB_INTERNAL'),
    ('public.guard_bcr_global_suppression()', 'DB_INTERNAL'),
    ('public.guard_campaign_activation()', 'DB_INTERNAL'),
    ('public.guard_deal_creation()', 'DB_INTERNAL'),
    ('public.guard_demo_creation()', 'DB_INTERNAL'),
    ('public.guard_email_queue_single_campaign()', 'DB_INTERNAL'),
    ('public.guard_proposal_creation()', 'DB_INTERNAL'),
    ('public.halfvec(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_accum(double precision[], halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_add(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_avg(double precision[])', 'DB_INTERNAL'),
    ('public.halfvec_cmp(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_combine(double precision[], double precision[])', 'DB_INTERNAL'),
    ('public.halfvec_concat(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_eq(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_ge(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_gt(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.halfvec_l2_squared_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_le(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_lt(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_mul(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_ne(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_negative_inner_product(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_out(halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.halfvec_send(halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_spherical_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_sub(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_to_float4(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_to_sparsevec(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_to_vector(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.hamming_distance(bit, bit)', 'DB_INTERNAL'),
    ('public.handle_availability_override_change()', 'DB_INTERNAL'),
    ('public.handle_deal_won()', 'DB_INTERNAL'),
    ('public.handle_email_bounce()', 'DB_INTERNAL'),
    ('public.handle_new_communication()', 'DB_INTERNAL'),
    ('public.handle_new_user()', 'DB_INTERNAL'),
    ('public.handle_payment_received()', 'DB_INTERNAL'),
    ('public.handle_supplier_status_change()', 'DB_INTERNAL'),
    ('public.has_live_ready_inbox(text)', 'DB_INTERNAL'),
    ('public.has_role(uuid, app_role)', 'DB_INTERNAL'),
    ('public.healthcare_set_updated_at()', 'DB_INTERNAL'),
    ('public.hnsw_bit_support(internal)', 'DB_INTERNAL'),
    ('public.hnsw_halfvec_support(internal)', 'DB_INTERNAL'),
    ('public.hnsw_sparsevec_support(internal)', 'DB_INTERNAL'),
    ('public.hnswhandler(internal)', 'DB_INTERNAL'),
    ('public.hwc_touch_updated_at()', 'DB_INTERNAL'),
    ('public.inbox_is_live_ready(uuid)', 'DEAD_OR_LEGACY'),
    ('public.inbox_set_provider_blocked(uuid, timestamp with time zone, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.inbox_warmup_limit(uuid)', 'DEAD_OR_LEGACY'),
    ('public.inner_product(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.inner_product(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.inner_product(vector, vector)', 'DB_INTERNAL'),
    ('public.is_agent_live_setting_enabled(text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.is_feature_enabled(text, text)', 'DB_INTERNAL'),
    ('public.is_founder()', 'DB_INTERNAL'),
    ('public.is_founder_or_admin(uuid)', 'DB_INTERNAL'),
    ('public.is_internal_email(text)', 'WEBHOOK_SYSTEM'),
    ('public.is_internal_identity(text)', 'DEAD_OR_LEGACY'),
    ('public.is_kill_switch_active()', 'DB_INTERNAL'),
    ('public.is_oversight_reviewer()', 'DB_INTERNAL'),
    ('public.ivfflat_bit_support(internal)', 'DB_INTERNAL'),
    ('public.ivfflat_halfvec_support(internal)', 'DB_INTERNAL'),
    ('public.ivfflathandler(internal)', 'DB_INTERNAL'),
    ('public.jaccard_distance(bit, bit)', 'DB_INTERNAL'),
    ('public.l1_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.l1_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.l1_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.l2_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.l2_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.l2_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.l2_norm(halfvec)', 'DB_INTERNAL'),
    ('public.l2_norm(sparsevec)', 'DB_INTERNAL'),
    ('public.l2_normalize(halfvec)', 'DB_INTERNAL'),
    ('public.l2_normalize(sparsevec)', 'DB_INTERNAL'),
    ('public.l2_normalize(vector)', 'DB_INTERNAL'),
    ('public.list_inbox_credentials_public(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.log_activity(text, text, text, uuid, text)', 'DB_INTERNAL'),
    ('public.log_business_override_change()', 'DB_INTERNAL'),
    ('public.log_compliance_event(text, compliance_entity_type, uuid, text, text, text, text, jsonb)', 'DB_INTERNAL'),
    ('public.log_demo_event(text, text, jsonb)', 'PUBLIC_ANON'),
    ('public.log_feature_flag_change()', 'DB_INTERNAL'),
    ('public.log_feature_skip(text, text, text, uuid)', 'DB_INTERNAL'),
    ('public.log_new_opportunity()', 'DB_INTERNAL'),
    ('public.log_new_proposal()', 'DB_INTERNAL'),
    ('public.log_new_support_request()', 'DB_INTERNAL'),
    ('public.log_system_config_change()', 'DB_INTERNAL'),
    ('public.log_system_event(text, text, uuid, text, system_event_severity, text, jsonb)', 'DB_INTERNAL'),
    ('public.log_system_mode_change()', 'DB_INTERNAL'),
    ('public.ma_audit_trigger()', 'DB_INTERNAL'),
    ('public.ma_generate_default_data_room(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.map_billionaire_network_evidence()', 'FOUNDER_ADMIN_ONLY'),
    ('public.mark_contact_for_founder_review(uuid, text)', 'DEAD_OR_LEGACY'),
    ('public.mark_send_failure(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.match_billionaire_wealth_snapshots(text, date)', 'FOUNDER_ADMIN_ONLY'),
    ('public.match_video_segments(text, vector, integer, uuid, uuid, numeric)', 'SERVICE_ROLE_INTERNAL'),
    ('public.mirror_comm_to_messages_and_invoke_ai()', 'DB_INTERNAL'),
    ('public.next_valid_send_time(uuid, timestamp with time zone)', 'DEAD_OR_LEGACY'),
    ('public.pick_inbox_for_business(text)', 'DEAD_OR_LEGACY'),
    ('public.pick_supplier_for_deal(uuid)', 'DEAD_OR_LEGACY'),
    ('public.priority_level_from_score(integer)', 'DB_INTERNAL'),
    ('public.priority_score_assignment(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_contact(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_conversation(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_deal(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_invoice(uuid)', 'DB_INTERNAL'),
    ('public.process_billionaire_enrichment_batch(integer)', 'DB_INTERNAL'),
    ('public.process_retry_queue()', 'DB_INTERNAL'),
    ('public.propagate_billionaire_institution_access()', 'DEAD_OR_LEGACY'),
    ('public.proposals_needing_followup()', 'DEAD_OR_LEGACY'),
    ('public.proposals_reconcile_crm()', 'DB_INTERNAL'),
    ('public.qtc_on_payment_succeeded()', 'DB_INTERNAL'),
    ('public.qtc_on_quote_accepted()', 'DB_INTERNAL'),
    ('public.qtc_payments_normalise()', 'DB_INTERNAL'),
    ('public.rebuild_billionaire_coverage()', 'FOUNDER_ADMIN_ONLY'),
    ('public.rebuild_full_manual()', 'FOUNDER_ADMIN_ONLY'),
    ('public.recalculate_priority(priority_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.recompute_all_inbox_performance()', 'DEAD_OR_LEGACY'),
    ('public.recompute_all_intent_scores()', 'DEAD_OR_LEGACY'),
    ('public.recompute_all_supplier_scores()', 'DEAD_OR_LEGACY'),
    ('public.recompute_business_risk_score(text)', 'DB_INTERNAL'),
    ('public.recompute_campaign_metrics(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.recompute_compliance_score(compliance_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.recompute_domain_reputation(text)', 'DB_INTERNAL'),
    ('public.recompute_inbox_performance(uuid)', 'DB_INTERNAL'),
    ('public.recompute_proposal_score(uuid)', 'DB_INTERNAL'),
    ('public.recompute_supplier_load(uuid)', 'DB_INTERNAL'),
    ('public.recompute_supplier_score(uuid)', 'DB_INTERNAL'),
    ('public.recompute_video_buyer_handover_ready(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.record_inbound_poll(uuid, boolean, text, integer)', 'WEBHOOK_SYSTEM'),
    ('public.record_inbox_test_send(uuid, boolean, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.record_system_change(text, uuid, text, text, text, integer)', 'DB_INTERNAL'),
    ('public.refresh_all_assignment_sla()', 'DEAD_OR_LEGACY'),
    ('public.refresh_all_business_risk_scores()', 'DEAD_OR_LEGACY'),
    ('public.release_ai_lease(text, boolean)', 'SERVICE_ROLE_INTERNAL'),
    ('public.release_portfolio_contact(uuid, text, text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.reset_inbox_hourly_counts()', 'DEAD_OR_LEGACY'),
    ('public.reset_inbox_send_counts()', 'DB_INTERNAL'),
    ('public.resolve_contact_by_email(text)', 'DEAD_OR_LEGACY'),
    ('public.resolve_contact_timezone(uuid)', 'DB_INTERNAL'),
    ('public.resolve_entity_country(uuid, text)', 'DB_INTERNAL'),
    ('public.run_billionaire_enrichment_batches(integer, integer)', 'DEAD_OR_LEGACY'),
    ('public.run_compliance_checks(compliance_entity_type, uuid)', 'DEAD_OR_LEGACY'),
    ('public.run_domain_protection_check()', 'DEAD_OR_LEGACY'),
    ('public.save_inbox_credentials(uuid, text, text, integer, text, text, text, text, text, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.save_inbox_inbound_config(uuid, text, text, integer, boolean, text, text, boolean, boolean, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.score_contact(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.score_proposal_quality(uuid)', 'DB_INTERNAL'),
    ('public.seed_supplier_records()', 'DB_INTERNAL'),
    ('public.set_assignment_sla()', 'DB_INTERNAL'),
    ('public.set_invoice_expected_amount()', 'DB_INTERNAL'),
    ('public.set_limit(real)', 'DB_INTERNAL'),
    ('public.set_proposal_followup_due()', 'DB_INTERNAL'),
    ('public.set_queue_priority_on_reply()', 'DB_INTERNAL'),
    ('public.set_system_mode(text)', 'DEAD_OR_LEGACY'),
    ('public.set_timezone_confidence()', 'DB_INTERNAL'),
    ('public.severity_weight(compliance_severity)', 'DB_INTERNAL'),
    ('public.show_limit()', 'DB_INTERNAL'),
    ('public.show_trgm(text)', 'DB_INTERNAL'),
    ('public.similarity(text, text)', 'DB_INTERNAL'),
    ('public.similarity_dist(text, text)', 'DB_INTERNAL'),
    ('public.similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.snapshot_deal_compliance_on_won()', 'DB_INTERNAL'),
    ('public.social_claim_distribution_job(uuid, uuid, text, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.social_relationship_claim_action(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.social_set_updated_at()', 'DB_INTERNAL'),
    ('public.sparsevec(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_cmp(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_eq(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_ge(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_gt(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.sparsevec_l2_squared_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_le(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_lt(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_ne(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_negative_inner_product(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_out(sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.sparsevec_send(sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_to_halfvec(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_to_vector(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.stamp_business_name_from_invoice()', 'DB_INTERNAL'),
    ('public.stamp_compliance_event_resolution()', 'DB_INTERNAL'),
    ('public.strict_word_similarity(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_dist_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_dist_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.subvector(halfvec, integer, integer)', 'DB_INTERNAL'),
    ('public.subvector(vector, integer, integer)', 'DB_INTERNAL'),
    ('public.suggest_replacement_supplier(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.supplier_list_assignments(text)', 'PUBLIC_ANON'),
    ('public.supplier_login_with_token(text)', 'PUBLIC_ANON'),
    ('public.supplier_portal_stats()', 'FOUNDER_ADMIN_ONLY'),
    ('public.supplier_update_assignment_status(text, uuid, text, text)', 'PUBLIC_ANON'),
    ('public.sync_domain_reputation_on_inbox_change()', 'DB_INTERNAL'),
    ('public.sync_supplier_availability_from_assignment()', 'DB_INTERNAL'),
    ('public.tg_liftor_recovery_actions_append_only()', 'DB_INTERNAL'),
    ('public.tg_liftor_snapshots_immutable()', 'DB_INTERNAL'),
    ('public.tg_mwi_touch_updated_at()', 'DB_INTERNAL'),
    ('public.tg_set_updated_at()', 'DB_INTERNAL'),
    ('public.touch_acquisition_funding_updated_at()', 'DB_INTERNAL'),
    ('public.touch_updated_at()', 'DB_INTERNAL'),
    ('public.trg_compliance_assignment()', 'DB_INTERNAL'),
    ('public.trg_compliance_communication()', 'DB_INTERNAL'),
    ('public.trg_compliance_contact()', 'DB_INTERNAL'),
    ('public.trg_compliance_demo()', 'DB_INTERNAL'),
    ('public.trg_compliance_invoice()', 'DB_INTERNAL'),
    ('public.trg_compliance_payment()', 'DB_INTERNAL'),
    ('public.trg_compliance_proposal()', 'DB_INTERNAL'),
    ('public.trg_priority_assignment()', 'DB_INTERNAL'),
    ('public.trg_priority_communication()', 'DB_INTERNAL'),
    ('public.trg_priority_conversation()', 'DB_INTERNAL'),
    ('public.trg_priority_deal()', 'DB_INTERNAL'),
    ('public.trg_priority_demo_event()', 'DB_INTERNAL'),
    ('public.trg_priority_from_compliance()', 'DB_INTERNAL'),
    ('public.trg_priority_invoice()', 'DB_INTERNAL'),
    ('public.trg_recompute_score_on_demo_event()', 'DB_INTERNAL'),
    ('public.trg_recompute_supplier_load()', 'DB_INTERNAL'),
    ('public.trg_recompute_supplier_score_on_assignment()', 'DB_INTERNAL'),
    ('public.trg_reputation_from_email_event()', 'DB_INTERNAL'),
    ('public.trg_score_proposal_quality()', 'DB_INTERNAL'),
    ('public.trg_spam_on_dnc()', 'DB_INTERNAL'),
    ('public.try_auto_assign_supplier_on_deal_won()', 'DB_INTERNAL'),
    ('public.update_updated_at_column()', 'DB_INTERNAL'),
    ('public.upsert_contact(text, text, text, text, text, text, uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_campaign_activation(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_full_system_coverage()', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_go_live_readiness()', 'DEAD_OR_LEGACY'),
    ('public.validate_inbox_mapping(uuid)', 'WEBHOOK_SYSTEM'),
    ('public.validate_runtime_vs_documentation()', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_system_integrity()', 'DEAD_OR_LEGACY'),
    ('public.vector(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_accum(double precision[], vector)', 'DB_INTERNAL'),
    ('public.vector_add(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_avg(double precision[])', 'DB_INTERNAL'),
    ('public.vector_cmp(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_combine(double precision[], double precision[])', 'DB_INTERNAL'),
    ('public.vector_concat(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_dims(halfvec)', 'DB_INTERNAL'),
    ('public.vector_dims(vector)', 'DB_INTERNAL'),
    ('public.vector_eq(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_ge(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_gt(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.vector_l2_squared_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_le(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_lt(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_mul(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_ne(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_negative_inner_product(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_norm(vector)', 'DB_INTERNAL'),
    ('public.vector_out(vector)', 'DB_INTERNAL'),
    ('public.vector_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.vector_send(vector)', 'DB_INTERNAL'),
    ('public.vector_spherical_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_sub(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_to_float4(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_to_halfvec(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_to_sparsevec(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.video_library_touch_updated_at()', 'DB_INTERNAL'),
    ('public.word_similarity(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_dist_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_dist_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.worker_has_active_window(uuid, text)', 'DB_INTERNAL')
), live AS (
  SELECT
    p.oid::text AS function_oid,
    format('%I.%I(%s)', n.nspname, p.proname, COALESCE(args.identity_types, '')) AS typed_signature,
    p.proname AS function_name,
    pg_get_function_identity_arguments(p.oid) AS identity_arguments,
    pg_get_function_arguments(p.oid) AS arguments_with_defaults,
    pg_get_userbyid(p.proowner) AS owner,
    l.lanname AS language,
    p.prosecdef AS security_definer,
    p.provolatile AS volatility,
    p.proconfig AS configured_settings,
    p.proacl::text AS raw_acl,
    COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'acl_ordinal', acl_item.ordinal,
        'grantee', CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,
        'grantor', pg_get_userbyid(a.grantor),
        'privilege', a.privilege_type,
        'grantable', a.is_grantable
      ) ORDER BY acl_item.ordinal, a.grantee, a.grantor, a.privilege_type)
      FROM unnest(COALESCE(p.proacl, acldefault('f', p.proowner)))
        WITH ORDINALITY AS acl_item(item, ordinal)
      CROSS JOIN LATERAL aclexplode(ARRAY[acl_item.item]) AS a
    ), '[]'::jsonb) AS acl_entries,
    EXISTS (
      SELECT 1 FROM aclexplode(COALESCE(p.proacl, acldefault('f', p.proowner))) AS a
      WHERE a.grantee = 0 AND a.privilege_type = 'EXECUTE'
    ) AS public_execute,
    has_function_privilege('anon', p.oid, 'EXECUTE') AS anon_execute,
    has_function_privilege('authenticated', p.oid, 'EXECUTE') AS authenticated_execute,
    has_function_privilege('service_role', p.oid, 'EXECUTE') AS service_role_execute,
    md5(pg_get_functiondef(p.oid)) AS pg_get_functiondef_md5,
    md5(p.prosrc) AS prosrc_md5,
    pg_get_functiondef(p.oid) AS exact_definition,
    c.classification
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  JOIN pg_language l ON l.oid = p.prolang
  LEFT JOIN classified c ON c.typed_signature = format('%I.%I(%s)', n.nspname, p.proname, COALESCE((
    SELECT string_agg(format_type(a, NULL), ', ' ORDER BY u.ordinality)
    FROM unnest(p.proargtypes::oid[]) WITH ORDINALITY AS u(a, ordinality)
  ), ''))
  LEFT JOIN LATERAL (
    SELECT string_agg(format_type(a, NULL), ', ' ORDER BY u.ordinality) AS identity_types
    FROM unnest(p.proargtypes::oid[]) WITH ORDINALITY AS u(a, ordinality)
  ) args ON true
  WHERE n.nspname = 'public' AND p.prokind = 'f'
)
SELECT
  function_oid, typed_signature, function_name, identity_arguments, arguments_with_defaults,
  owner, language, security_definer, volatility, configured_settings, raw_acl, acl_entries,
  public_execute, anon_execute, authenticated_execute, service_role_execute,
  pg_get_functiondef_md5, prosrc_md5, classification, exact_definition
FROM live
ORDER BY typed_signature;

-- Future EXECUTE defaults are separate from current function ACLs. Capture all
-- global and public-schema defaults so a schema-specific revocation is not
-- mistaken for proof that the global PUBLIC default has been removed.
SELECT
  d.defaclrole::regrole::text AS owner_role,
  CASE WHEN d.defaclnamespace = 0 THEN '<global>' ELSE n.nspname END AS schema_name,
  d.defaclobjtype AS object_type,
  d.defaclacl::text AS raw_default_acl,
  COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'grantee', CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,
      'grantor', pg_get_userbyid(a.grantor),
      'privilege', a.privilege_type,
      'grantable', a.is_grantable
    ) ORDER BY a.grantee, a.grantor, a.privilege_type)
    FROM aclexplode(d.defaclacl) a
  ), '[]'::jsonb) AS default_acl_entries
FROM pg_default_acl d
LEFT JOIN pg_namespace n ON n.oid = d.defaclnamespace
WHERE d.defaclobjtype = 'f'
  AND (d.defaclnamespace = 0 OR n.nspname = 'public')
ORDER BY owner_role, schema_name;

SELECT 'supabase_migrations.schema_migrations' AS migration_history_relation,
       to_regclass('supabase_migrations.schema_migrations')::text AS visible_relation;

-- Capture the exact migration-history row without assuming a version/name
-- column layout. This remains read-only and works across Supabase history table
-- variants. If the relation is unavailable, the result says so explicitly.
SELECT to_regclass('supabase_migrations.schema_migrations') IS NOT NULL AS stage1b_history_visible \gset
\if :stage1b_history_visible
SELECT COALESCE(
         jsonb_agg(to_jsonb(m) ORDER BY to_jsonb(m)::text),
         '[]'::jsonb
       ) AS matching_stage1b_migration_history_rows
FROM supabase_migrations.schema_migrations AS m
WHERE to_jsonb(m)::text LIKE '%20260923130000_stage1b_rpc_authorization_hardening%';
\else
SELECT 'migration history relation not visible to this role' AS matching_stage1b_migration_history_rows;
\endif

WITH classified(typed_signature, classification) AS (
  VALUES
    ('public._is_founder_or_admin()', 'DB_INTERNAL'),
    ('public.accept_proposal_by_token(text)', 'PUBLIC_ANON'),
    ('public.acquire_ai_lease(text, uuid, uuid, integer, integer, text, text, integer)', 'SERVICE_ROLE_INTERNAL'),
    ('public.activate_outreach_campaign(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.ai_actions_today(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_release(text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_reserve(text, text, integer, text, uuid, text, text[], jsonb)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_settle(text, integer, text[], text[], jsonb)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_credit_status()', 'FOUNDER_ADMIN_ONLY'),
    ('public.apollo_decrypt_key(bytea, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apollo_encrypt_key(text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.apply_reply_stop_suppression(uuid, text, text)', 'DEAD_OR_LEGACY'),
    ('public.apply_reputation_event(uuid, uuid, reputation_event_type, text)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_halfvec(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_sparsevec(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(double precision[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(integer[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(numeric[], integer, boolean)', 'DB_INTERNAL'),
    ('public.array_to_vector(real[], integer, boolean)', 'DB_INTERNAL'),
    ('public.assign_inbox_for_contact(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.auto_create_exit_intelligence_profile()', 'DB_INTERNAL'),
    ('public.auto_partial_rebuild()', 'DEAD_OR_LEGACY'),
    ('public.auto_resolve_system_events()', 'DB_INTERNAL'),
    ('public.bi_normalize_name(text)', 'DB_INTERNAL'),
    ('public.binary_quantize(halfvec)', 'DB_INTERNAL'),
    ('public.binary_quantize(vector)', 'DB_INTERNAL'),
    ('public.block_activation_log_mutation()', 'DB_INTERNAL'),
    ('public.bump_inbox_send_count()', 'DB_INTERNAL'),
    ('public.bump_rule_hit_count()', 'DB_INTERNAL'),
    ('public.cancel_queue_on_inbound_comm()', 'DB_INTERNAL'),
    ('public.cancel_queue_on_reply()', 'DB_INTERNAL'),
    ('public.check_outreach_allowed(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.check_outreach_allowed(uuid, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.check_send_throttle(uuid, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.claim_portfolio_contact(uuid, text, text, uuid, boolean, text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.cleanup_stale_ai_leases()', 'FOUNDER_ADMIN_ONLY'),
    ('public.compare_system_versions(integer, integer)', 'FOUNDER_ADMIN_ONLY'),
    ('public.compliance_check_assignment(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_contact(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_demo(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_invoice(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_outbound_communication(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_payment(uuid)', 'DB_INTERNAL'),
    ('public.compliance_check_proposal(uuid)', 'DB_INTERNAL'),
    ('public.compliance_score_for(text, uuid)', 'DB_INTERNAL'),
    ('public.compute_assignment_sla(date, assignment_status)', 'DB_INTERNAL'),
    ('public.compute_intent_score(uuid)', 'DB_INTERNAL'),
    ('public.compute_system_health()', 'DB_INTERNAL'),
    ('public.cosine_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.cosine_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.cosine_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.country_to_timezone(text)', 'DB_INTERNAL'),
    ('public.crm_match_interaction_preview(uuid, uuid, text, text, text, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.current_worker_id()', 'DB_INTERNAL'),
    ('public.customer_sales_link_contact_by_email(text)', 'WEBHOOK_SYSTEM'),
    ('public.derive_billionaire_route_evidence_states()', 'DB_INTERNAL'),
    ('public.detect_anomalies()', 'FOUNDER_ADMIN_ONLY'),
    ('public.detect_orphan_content()', 'FOUNDER_ADMIN_ONLY'),
    ('public.domain_for_inbox(uuid)', 'DB_INTERNAL'),
    ('public.eligible_suppliers_for_deal(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.enforce_founder_approval_for_buyer_outreach()', 'DB_INTERNAL'),
    ('public.enforce_founder_approval_for_warm_up_action()', 'DB_INTERNAL'),
    ('public.enforce_inbox_ramp(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.enrich_all_contacts()', 'DEAD_OR_LEGACY'),
    ('public.enrich_contact(uuid)', 'DB_INTERNAL'),
    ('public.escalate_retry_failure(uuid)', 'DEAD_OR_LEGACY'),
    ('public.evaluate_ai_reply(text)', 'DEAD_OR_LEGACY'),
    ('public.expire_demos()', 'DB_INTERNAL'),
    ('public.expire_inactive_conversations()', 'SERVICE_ROLE_INTERNAL'),
    ('public.export_full_system_snapshot()', 'FOUNDER_ADMIN_ONLY'),
    ('public.finance_mark_overdue_invoices()', 'SERVICE_ROLE_INTERNAL'),
    ('public.finance_target_vs_actual(text, date)', 'FOUNDER_ADMIN_ONLY'),
    ('public.flag_idle_assignments()', 'DEAD_OR_LEGACY'),
    ('public.founder_confirm_assignment(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.generate_invoice_number()', 'DEAD_OR_LEGACY'),
    ('public.generate_system_tasks_from_priority(priority_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.get_active_execution_mode(text)', 'DB_INTERNAL'),
    ('public.get_business_outbound_status(text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_contact_360_summary(uuid, uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_contact_timeline(uuid, uuid, integer)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_interaction_ledger_summary(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_crm_relationship_timeline(uuid, integer)', 'DEAD_OR_LEGACY'),
    ('public.get_customer_quarterly_report_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_customer_survey_request_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_inbox_credentials_for_send(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_inbox_imap_credentials(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_outbound_status()', 'FOUNDER_ADMIN_ONLY'),
    ('public.get_outreach_send_cron_status()', 'SERVICE_ROLE_INTERNAL'),
    ('public.get_proposal_by_token(text)', 'PUBLIC_ANON'),
    ('public.get_system_mode()', 'DB_INTERNAL'),
    ('public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gin_extract_value_trgm(text, internal)', 'DB_INTERNAL'),
    ('public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gsm_mailbox_is_campaign_ready(text, text, text, text, text, text, integer, integer, boolean, boolean, text, text, text)', 'DEAD_OR_LEGACY'),
    ('public.gsm_touch_updated_at()', 'DB_INTERNAL'),
    ('public.gtrgm_compress(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_consistent(internal, text, smallint, oid, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_decompress(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_distance(internal, text, smallint, oid, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_in(cstring)', 'DB_INTERNAL'),
    ('public.gtrgm_options(internal)', 'DB_INTERNAL'),
    ('public.gtrgm_out(gtrgm)', 'DB_INTERNAL'),
    ('public.gtrgm_penalty(internal, internal, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_picksplit(internal, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_same(gtrgm, gtrgm, internal)', 'DB_INTERNAL'),
    ('public.gtrgm_union(internal, internal)', 'DB_INTERNAL'),
    ('public.guard_assignment_creation()', 'DB_INTERNAL'),
    ('public.guard_assignment_supplier_approved()', 'DB_INTERNAL'),
    ('public.guard_bcr_global_suppression()', 'DB_INTERNAL'),
    ('public.guard_campaign_activation()', 'DB_INTERNAL'),
    ('public.guard_deal_creation()', 'DB_INTERNAL'),
    ('public.guard_demo_creation()', 'DB_INTERNAL'),
    ('public.guard_email_queue_single_campaign()', 'DB_INTERNAL'),
    ('public.guard_proposal_creation()', 'DB_INTERNAL'),
    ('public.halfvec(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_accum(double precision[], halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_add(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_avg(double precision[])', 'DB_INTERNAL'),
    ('public.halfvec_cmp(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_combine(double precision[], double precision[])', 'DB_INTERNAL'),
    ('public.halfvec_concat(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_eq(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_ge(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_gt(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.halfvec_l2_squared_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_le(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_lt(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_mul(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_ne(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_negative_inner_product(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_out(halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.halfvec_send(halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_spherical_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_sub(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.halfvec_to_float4(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_to_sparsevec(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_to_vector(halfvec, integer, boolean)', 'DB_INTERNAL'),
    ('public.halfvec_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.hamming_distance(bit, bit)', 'DB_INTERNAL'),
    ('public.handle_availability_override_change()', 'DB_INTERNAL'),
    ('public.handle_deal_won()', 'DB_INTERNAL'),
    ('public.handle_email_bounce()', 'DB_INTERNAL'),
    ('public.handle_new_communication()', 'DB_INTERNAL'),
    ('public.handle_new_user()', 'DB_INTERNAL'),
    ('public.handle_payment_received()', 'DB_INTERNAL'),
    ('public.handle_supplier_status_change()', 'DB_INTERNAL'),
    ('public.has_live_ready_inbox(text)', 'DB_INTERNAL'),
    ('public.has_role(uuid, app_role)', 'DB_INTERNAL'),
    ('public.healthcare_set_updated_at()', 'DB_INTERNAL'),
    ('public.hnsw_bit_support(internal)', 'DB_INTERNAL'),
    ('public.hnsw_halfvec_support(internal)', 'DB_INTERNAL'),
    ('public.hnsw_sparsevec_support(internal)', 'DB_INTERNAL'),
    ('public.hnswhandler(internal)', 'DB_INTERNAL'),
    ('public.hwc_touch_updated_at()', 'DB_INTERNAL'),
    ('public.inbox_is_live_ready(uuid)', 'DEAD_OR_LEGACY'),
    ('public.inbox_set_provider_blocked(uuid, timestamp with time zone, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.inbox_warmup_limit(uuid)', 'DEAD_OR_LEGACY'),
    ('public.inner_product(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.inner_product(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.inner_product(vector, vector)', 'DB_INTERNAL'),
    ('public.is_agent_live_setting_enabled(text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.is_feature_enabled(text, text)', 'DB_INTERNAL'),
    ('public.is_founder()', 'DB_INTERNAL'),
    ('public.is_founder_or_admin(uuid)', 'DB_INTERNAL'),
    ('public.is_internal_email(text)', 'WEBHOOK_SYSTEM'),
    ('public.is_internal_identity(text)', 'DEAD_OR_LEGACY'),
    ('public.is_kill_switch_active()', 'DB_INTERNAL'),
    ('public.is_oversight_reviewer()', 'DB_INTERNAL'),
    ('public.ivfflat_bit_support(internal)', 'DB_INTERNAL'),
    ('public.ivfflat_halfvec_support(internal)', 'DB_INTERNAL'),
    ('public.ivfflathandler(internal)', 'DB_INTERNAL'),
    ('public.jaccard_distance(bit, bit)', 'DB_INTERNAL'),
    ('public.l1_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.l1_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.l1_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.l2_distance(halfvec, halfvec)', 'DB_INTERNAL'),
    ('public.l2_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.l2_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.l2_norm(halfvec)', 'DB_INTERNAL'),
    ('public.l2_norm(sparsevec)', 'DB_INTERNAL'),
    ('public.l2_normalize(halfvec)', 'DB_INTERNAL'),
    ('public.l2_normalize(sparsevec)', 'DB_INTERNAL'),
    ('public.l2_normalize(vector)', 'DB_INTERNAL'),
    ('public.list_inbox_credentials_public(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.log_activity(text, text, text, uuid, text)', 'DB_INTERNAL'),
    ('public.log_business_override_change()', 'DB_INTERNAL'),
    ('public.log_compliance_event(text, compliance_entity_type, uuid, text, text, text, text, jsonb)', 'DB_INTERNAL'),
    ('public.log_demo_event(text, text, jsonb)', 'PUBLIC_ANON'),
    ('public.log_feature_flag_change()', 'DB_INTERNAL'),
    ('public.log_feature_skip(text, text, text, uuid)', 'DB_INTERNAL'),
    ('public.log_new_opportunity()', 'DB_INTERNAL'),
    ('public.log_new_proposal()', 'DB_INTERNAL'),
    ('public.log_new_support_request()', 'DB_INTERNAL'),
    ('public.log_system_config_change()', 'DB_INTERNAL'),
    ('public.log_system_event(text, text, uuid, text, system_event_severity, text, jsonb)', 'DB_INTERNAL'),
    ('public.log_system_mode_change()', 'DB_INTERNAL'),
    ('public.ma_audit_trigger()', 'DB_INTERNAL'),
    ('public.ma_generate_default_data_room(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.map_billionaire_network_evidence()', 'FOUNDER_ADMIN_ONLY'),
    ('public.mark_contact_for_founder_review(uuid, text)', 'DEAD_OR_LEGACY'),
    ('public.mark_send_failure(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.match_billionaire_wealth_snapshots(text, date)', 'FOUNDER_ADMIN_ONLY'),
    ('public.match_video_segments(text, vector, integer, uuid, uuid, numeric)', 'SERVICE_ROLE_INTERNAL'),
    ('public.mirror_comm_to_messages_and_invoke_ai()', 'DB_INTERNAL'),
    ('public.next_valid_send_time(uuid, timestamp with time zone)', 'DEAD_OR_LEGACY'),
    ('public.pick_inbox_for_business(text)', 'DEAD_OR_LEGACY'),
    ('public.pick_supplier_for_deal(uuid)', 'DEAD_OR_LEGACY'),
    ('public.priority_level_from_score(integer)', 'DB_INTERNAL'),
    ('public.priority_score_assignment(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_contact(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_conversation(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_deal(uuid)', 'DB_INTERNAL'),
    ('public.priority_score_invoice(uuid)', 'DB_INTERNAL'),
    ('public.process_billionaire_enrichment_batch(integer)', 'DB_INTERNAL'),
    ('public.process_retry_queue()', 'DB_INTERNAL'),
    ('public.propagate_billionaire_institution_access()', 'DEAD_OR_LEGACY'),
    ('public.proposals_needing_followup()', 'DEAD_OR_LEGACY'),
    ('public.proposals_reconcile_crm()', 'DB_INTERNAL'),
    ('public.qtc_on_payment_succeeded()', 'DB_INTERNAL'),
    ('public.qtc_on_quote_accepted()', 'DB_INTERNAL'),
    ('public.qtc_payments_normalise()', 'DB_INTERNAL'),
    ('public.rebuild_billionaire_coverage()', 'FOUNDER_ADMIN_ONLY'),
    ('public.rebuild_full_manual()', 'FOUNDER_ADMIN_ONLY'),
    ('public.recalculate_priority(priority_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.recompute_all_inbox_performance()', 'DEAD_OR_LEGACY'),
    ('public.recompute_all_intent_scores()', 'DEAD_OR_LEGACY'),
    ('public.recompute_all_supplier_scores()', 'DEAD_OR_LEGACY'),
    ('public.recompute_business_risk_score(text)', 'DB_INTERNAL'),
    ('public.recompute_campaign_metrics(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.recompute_compliance_score(compliance_entity_type, uuid)', 'DB_INTERNAL'),
    ('public.recompute_domain_reputation(text)', 'DB_INTERNAL'),
    ('public.recompute_inbox_performance(uuid)', 'DB_INTERNAL'),
    ('public.recompute_proposal_score(uuid)', 'DB_INTERNAL'),
    ('public.recompute_supplier_load(uuid)', 'DB_INTERNAL'),
    ('public.recompute_supplier_score(uuid)', 'DB_INTERNAL'),
    ('public.recompute_video_buyer_handover_ready(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.record_inbound_poll(uuid, boolean, text, integer)', 'WEBHOOK_SYSTEM'),
    ('public.record_inbox_test_send(uuid, boolean, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.record_system_change(text, uuid, text, text, text, integer)', 'DB_INTERNAL'),
    ('public.refresh_all_assignment_sla()', 'DEAD_OR_LEGACY'),
    ('public.refresh_all_business_risk_scores()', 'DEAD_OR_LEGACY'),
    ('public.release_ai_lease(text, boolean)', 'SERVICE_ROLE_INTERNAL'),
    ('public.release_portfolio_contact(uuid, text, text)', 'FOUNDER_ADMIN_ONLY'),
    ('public.reset_inbox_hourly_counts()', 'DEAD_OR_LEGACY'),
    ('public.reset_inbox_send_counts()', 'DB_INTERNAL'),
    ('public.resolve_contact_by_email(text)', 'DEAD_OR_LEGACY'),
    ('public.resolve_contact_timezone(uuid)', 'DB_INTERNAL'),
    ('public.resolve_entity_country(uuid, text)', 'DB_INTERNAL'),
    ('public.run_billionaire_enrichment_batches(integer, integer)', 'DEAD_OR_LEGACY'),
    ('public.run_compliance_checks(compliance_entity_type, uuid)', 'DEAD_OR_LEGACY'),
    ('public.run_domain_protection_check()', 'DEAD_OR_LEGACY'),
    ('public.save_inbox_credentials(uuid, text, text, integer, text, text, text, text, text, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.save_inbox_inbound_config(uuid, text, text, integer, boolean, text, text, boolean, boolean, text, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.score_contact(uuid, text)', 'SERVICE_ROLE_INTERNAL'),
    ('public.score_proposal_quality(uuid)', 'DB_INTERNAL'),
    ('public.seed_supplier_records()', 'DB_INTERNAL'),
    ('public.set_assignment_sla()', 'DB_INTERNAL'),
    ('public.set_invoice_expected_amount()', 'DB_INTERNAL'),
    ('public.set_limit(real)', 'DB_INTERNAL'),
    ('public.set_proposal_followup_due()', 'DB_INTERNAL'),
    ('public.set_queue_priority_on_reply()', 'DB_INTERNAL'),
    ('public.set_system_mode(text)', 'DEAD_OR_LEGACY'),
    ('public.set_timezone_confidence()', 'DB_INTERNAL'),
    ('public.severity_weight(compliance_severity)', 'DB_INTERNAL'),
    ('public.show_limit()', 'DB_INTERNAL'),
    ('public.show_trgm(text)', 'DB_INTERNAL'),
    ('public.similarity(text, text)', 'DB_INTERNAL'),
    ('public.similarity_dist(text, text)', 'DB_INTERNAL'),
    ('public.similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.snapshot_deal_compliance_on_won()', 'DB_INTERNAL'),
    ('public.social_claim_distribution_job(uuid, uuid, text, uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.social_relationship_claim_action(uuid)', 'SERVICE_ROLE_INTERNAL'),
    ('public.social_set_updated_at()', 'DB_INTERNAL'),
    ('public.sparsevec(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_cmp(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_eq(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_ge(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_gt(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.sparsevec_l2_squared_distance(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_le(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_lt(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_ne(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_negative_inner_product(sparsevec, sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_out(sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.sparsevec_send(sparsevec)', 'DB_INTERNAL'),
    ('public.sparsevec_to_halfvec(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_to_vector(sparsevec, integer, boolean)', 'DB_INTERNAL'),
    ('public.sparsevec_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.stamp_business_name_from_invoice()', 'DB_INTERNAL'),
    ('public.stamp_compliance_event_resolution()', 'DB_INTERNAL'),
    ('public.strict_word_similarity(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_dist_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_dist_op(text, text)', 'DB_INTERNAL'),
    ('public.strict_word_similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.subvector(halfvec, integer, integer)', 'DB_INTERNAL'),
    ('public.subvector(vector, integer, integer)', 'DB_INTERNAL'),
    ('public.suggest_replacement_supplier(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.supplier_list_assignments(text)', 'PUBLIC_ANON'),
    ('public.supplier_login_with_token(text)', 'PUBLIC_ANON'),
    ('public.supplier_portal_stats()', 'FOUNDER_ADMIN_ONLY'),
    ('public.supplier_update_assignment_status(text, uuid, text, text)', 'PUBLIC_ANON'),
    ('public.sync_domain_reputation_on_inbox_change()', 'DB_INTERNAL'),
    ('public.sync_supplier_availability_from_assignment()', 'DB_INTERNAL'),
    ('public.tg_liftor_recovery_actions_append_only()', 'DB_INTERNAL'),
    ('public.tg_liftor_snapshots_immutable()', 'DB_INTERNAL'),
    ('public.tg_mwi_touch_updated_at()', 'DB_INTERNAL'),
    ('public.tg_set_updated_at()', 'DB_INTERNAL'),
    ('public.touch_acquisition_funding_updated_at()', 'DB_INTERNAL'),
    ('public.touch_updated_at()', 'DB_INTERNAL'),
    ('public.trg_compliance_assignment()', 'DB_INTERNAL'),
    ('public.trg_compliance_communication()', 'DB_INTERNAL'),
    ('public.trg_compliance_contact()', 'DB_INTERNAL'),
    ('public.trg_compliance_demo()', 'DB_INTERNAL'),
    ('public.trg_compliance_invoice()', 'DB_INTERNAL'),
    ('public.trg_compliance_payment()', 'DB_INTERNAL'),
    ('public.trg_compliance_proposal()', 'DB_INTERNAL'),
    ('public.trg_priority_assignment()', 'DB_INTERNAL'),
    ('public.trg_priority_communication()', 'DB_INTERNAL'),
    ('public.trg_priority_conversation()', 'DB_INTERNAL'),
    ('public.trg_priority_deal()', 'DB_INTERNAL'),
    ('public.trg_priority_demo_event()', 'DB_INTERNAL'),
    ('public.trg_priority_from_compliance()', 'DB_INTERNAL'),
    ('public.trg_priority_invoice()', 'DB_INTERNAL'),
    ('public.trg_recompute_score_on_demo_event()', 'DB_INTERNAL'),
    ('public.trg_recompute_supplier_load()', 'DB_INTERNAL'),
    ('public.trg_recompute_supplier_score_on_assignment()', 'DB_INTERNAL'),
    ('public.trg_reputation_from_email_event()', 'DB_INTERNAL'),
    ('public.trg_score_proposal_quality()', 'DB_INTERNAL'),
    ('public.trg_spam_on_dnc()', 'DB_INTERNAL'),
    ('public.try_auto_assign_supplier_on_deal_won()', 'DB_INTERNAL'),
    ('public.update_updated_at_column()', 'DB_INTERNAL'),
    ('public.upsert_contact(text, text, text, text, text, text, uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_campaign_activation(uuid)', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_full_system_coverage()', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_go_live_readiness()', 'DEAD_OR_LEGACY'),
    ('public.validate_inbox_mapping(uuid)', 'WEBHOOK_SYSTEM'),
    ('public.validate_runtime_vs_documentation()', 'FOUNDER_ADMIN_ONLY'),
    ('public.validate_system_integrity()', 'DEAD_OR_LEGACY'),
    ('public.vector(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_accum(double precision[], vector)', 'DB_INTERNAL'),
    ('public.vector_add(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_avg(double precision[])', 'DB_INTERNAL'),
    ('public.vector_cmp(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_combine(double precision[], double precision[])', 'DB_INTERNAL'),
    ('public.vector_concat(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_dims(halfvec)', 'DB_INTERNAL'),
    ('public.vector_dims(vector)', 'DB_INTERNAL'),
    ('public.vector_eq(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_ge(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_gt(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_in(cstring, oid, integer)', 'DB_INTERNAL'),
    ('public.vector_l2_squared_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_le(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_lt(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_mul(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_ne(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_negative_inner_product(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_norm(vector)', 'DB_INTERNAL'),
    ('public.vector_out(vector)', 'DB_INTERNAL'),
    ('public.vector_recv(internal, oid, integer)', 'DB_INTERNAL'),
    ('public.vector_send(vector)', 'DB_INTERNAL'),
    ('public.vector_spherical_distance(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_sub(vector, vector)', 'DB_INTERNAL'),
    ('public.vector_to_float4(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_to_halfvec(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_to_sparsevec(vector, integer, boolean)', 'DB_INTERNAL'),
    ('public.vector_typmod_in(cstring[])', 'DB_INTERNAL'),
    ('public.video_library_touch_updated_at()', 'DB_INTERNAL'),
    ('public.word_similarity(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_dist_commutator_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_dist_op(text, text)', 'DB_INTERNAL'),
    ('public.word_similarity_op(text, text)', 'DB_INTERNAL'),
    ('public.worker_has_active_window(uuid, text)', 'DB_INTERNAL')
), live AS (
  SELECT
    p.oid::text AS function_oid,
    format('%I.%I(%s)', n.nspname, p.proname, COALESCE((
      SELECT string_agg(format_type(a, NULL), ', ' ORDER BY u.ordinality)
      FROM unnest(p.proargtypes::oid[]) WITH ORDINALITY AS u(a, ordinality)
    ), '')) AS typed_signature,
    pg_get_userbyid(p.proowner) AS owner,
    l.lanname AS language,
    p.prosecdef AS security_definer,
    p.proconfig AS configured_settings,
    p.proacl::text AS raw_acl,
    has_function_privilege('anon', p.oid, 'EXECUTE') AS anon_execute,
    has_function_privilege('authenticated', p.oid, 'EXECUTE') AS authenticated_execute,
    md5(pg_get_functiondef(p.oid)) AS pg_get_functiondef_md5,
    pg_get_functiondef(p.oid) AS exact_definition,
    c.classification
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  JOIN pg_language l ON l.oid = p.prolang
  LEFT JOIN classified c ON c.typed_signature = format('%I.%I(%s)', n.nspname, p.proname, COALESCE((
    SELECT string_agg(format_type(a, NULL), ', ' ORDER BY u.ordinality)
    FROM unnest(p.proargtypes::oid[]) WITH ORDINALITY AS u(a, ordinality)
  ), ''))
  WHERE n.nspname = 'public' AND p.prokind = 'f'
)
SELECT
  count(*) OVER () AS observed_anon_application_function_count,
  function_oid, typed_signature, owner, language, security_definer,
  configured_settings, raw_acl, anon_execute, authenticated_execute,
  pg_get_functiondef_md5, classification, exact_definition
FROM live
WHERE anon_execute
  AND NOT (language = 'c' AND owner = 'supabase_admin' AND NOT security_definer)
ORDER BY typed_signature;

WITH targets(typed_signature) AS (
  VALUES
    ('public.get_business_outbound_status(text)'),
    ('public.get_outbound_status()'),
    ('public.activate_outreach_campaign(uuid)'),
    ('public.apollo_credit_status()'),
    ('public.check_outreach_allowed(uuid)'),
    ('public.check_outreach_allowed(uuid, uuid)'),
    ('public.claim_portfolio_contact(uuid, text, text, uuid, boolean, text)'),
    ('public.cleanup_stale_ai_leases()'),
    ('public.compare_system_versions(integer, integer)'),
    ('public.crm_match_interaction_preview(uuid, uuid, text, text, text, uuid)'),
    ('public.detect_anomalies()'),
    ('public.detect_orphan_content()'),
    ('public.eligible_suppliers_for_deal(uuid)'),
    ('public.export_full_system_snapshot()'),
    ('public.finance_target_vs_actual(text, date)'),
    ('public.founder_confirm_assignment(uuid)'),
    ('public.get_crm_contact_360_summary(uuid, uuid)'),
    ('public.get_crm_contact_timeline(uuid, uuid, integer)'),
    ('public.get_crm_interaction_ledger_summary(uuid)'),
    ('public.has_role(uuid, app_role)'),
    ('public.is_founder_or_admin(uuid)'),
    ('public.ma_generate_default_data_room(uuid)'),
    ('public.map_billionaire_network_evidence()'),
    ('public.match_billionaire_wealth_snapshots(text, date)'),
    ('public.rebuild_billionaire_coverage()'),
    ('public.rebuild_full_manual()'),
    ('public.recompute_video_buyer_handover_ready(uuid)'),
    ('public.release_portfolio_contact(uuid, text, text)'),
    ('public.suggest_replacement_supplier(uuid)'),
    ('public.supplier_portal_stats()'),
    ('public.upsert_contact(text, text, text, text, text, text, uuid)'),
    ('public.validate_campaign_activation(uuid)'),
    ('public.validate_full_system_coverage()'),
    ('public.validate_runtime_vs_documentation()'),
    ('public.worker_has_active_window(uuid, text)')
), live AS (
  SELECT
    format('%I.%I(%s)', n.nspname, p.proname, COALESCE((
      SELECT string_agg(format_type(a, NULL), ', ' ORDER BY u.ordinality)
      FROM unnest(p.proargtypes::oid[]) WITH ORDINALITY AS u(a, ordinality)
    ), '')) AS typed_signature,
    pg_get_userbyid(p.proowner) AS owner,
    p.prosecdef AS security_definer,
    p.proconfig AS configured_settings,
    p.proacl::text AS raw_acl,
    md5(pg_get_functiondef(p.oid)) AS pg_get_functiondef_md5,
    pg_get_functiondef(p.oid) AS exact_definition
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind = 'f'
)
SELECT live.*
FROM live JOIN targets USING (typed_signature)
ORDER BY typed_signature;
